### ISSUE TITLE
authentication helpers with probing chain support

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/msrestazure-for-python#118]
design doc: https://github.com/Azure/azure-auth-wg/blob/master/doc/api_auth.md
More details to come, like class naming. We should at least detect the following sources

1. Detect we are in a VM with managed service identity
2. Detect environment variables like AZURE_CLIENT_ID, AZURE_CLIENT_SECRET
3. Detect the default auth code file path
4. Detect CLI's cached tokens

//cc: @mayurid  @lmazuel

**Comment by yugangw-msft** [comment]
@lmazuel, i will do the work to sort out all the technical details, particularly the right (fast) way to detect we are in a VM with MSI.
If you have any opinions/comments, please let me know.

**Comment by mayurid** [comment]
//cc: @binderjoe as well.

**Comment by lmazuel** [comment]
See azure-identity now
