### ISSUE TITLE
Correct way to have long-lived service principal credentials?

### ISSUE THREAD

**Issue by akx** [Azure/msrestazure-for-python#123]
I have a long-lived daemon, for which I'm currently caching a `ServicePrincipalCredentials` object, as otherwise every operation I'd do would cause

https://github.com/Azure/msrestazure-for-python/blob/b0ff648654009cfaaaaad5a933fe2a16cdb5ce75/msrestazure/azure_active_directory.py#L356-L370

to be called.

However, with this I eventually get

```python
  File "msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "azure/mgmt/compute/v2018_10_01/operations/virtual_machines_operations.py", line 903, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: ExpiredAuthenticationToken
Message: The access token expiry UTC time '12/14/2018 5:12:14 AM' is earlier than current UTC time '12/14/2018 5:56:24 AM'.
```

Searching for `ExpiredAuthenticationToken` yields no results in all of site-packages, so I assume nothing really handles this.

My current mitigation plan is to cache the `ServicePrincipalCredentials` object for a shorter time and reacquire it e.g. every hour. Is this the right way to go about it?

**Comment by lmazuel** [comment]
Hi @akx ,
You shouldn't need to cache the object, set_token should be called only when the token is expired. It's handled by our request-oauthlib library.

Do you have any reason to believe that set_token is called for each call? HTTP fiddler, or anything? If yes, I need to double-check.

Thank you

**Comment by lmazuel** [comment]
I looked at the code to be sure, see my comment in this line:
https://github.com/Azure/msrestazure-for-python/blob/bfd0b7b585c2eaf94b6ee12abb35a487fdbb984a/msrestazure/azure_active_directory.py#L199

ADAL is suppose to cache the token the token for us, so we can safely ask one at each call. If you see an actual auth call for each requests, that's a ADAL bug I need to declare.

**Comment by akx** [comment]
I haven't checked to be sure yet, but will do.

The ADAL context is constructed like

https://github.com/Azure/msrestazure-for-python/blob/bfd0b7b585c2eaf94b6ee12abb35a487fdbb984a/msrestazure/azure_active_directory.py#L110-L118

though, with `cache=self._cache`, and `self._cache` is read from `kwargs['cache']` in the `AADMixin` ctor:

https://github.com/Azure/msrestazure-for-python/blob/bfd0b7b585c2eaf94b6ee12abb35a487fdbb984a/msrestazure/azure_active_directory.py#L96

So if no cache is passed in, `adal` will always construct one: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/4b7297510c08c357f95a56ae6be73d8bdfc99e3a/adal/authentication_context.py#L113

With this in mind, it sounds like having a long-lived `ServicePrincipalCredentials` (or sharing a `TokenCache` at the very least) is the best practice?

**Comment by akx** [comment]
Okay – I double-checked, by adding logging to `requests.Session.request()`, and it does look like the token is acquired only once no matter how I'm instantiating `msrestazure.azure_active_directory.ServicePrincipalCredentials`.

I suppose the real question is why I'm getting `ExpiredAuthenticationToken` if ADAL/something else is supposed to refresh the token.

**Comment by akx** [comment]
The relevant bits of my `requirements.txt` (all pinned thanks to `pip-tools`) are

```
adal==1.2.0               # via msrestazure
asn1crypto==0.24.0        # via cryptography
azure-common==1.1.16      # via azure-mgmt-compute, azure-mgmt-network, azure-mgmt-resource
azure-mgmt-compute==4.3.1
azure-mgmt-network==2.3.0
azure-mgmt-nspkg==3.0.2   # via azure-mgmt-resource
azure-mgmt-resource==2.0.0
azure-nspkg==3.0.2        # via azure-mgmt-nspkg
certifi==2018.10.15
cffi==1.11.5              # via cryptography
chardet==3.0.4            # via requests
cryptography==2.4.1       # via adal
idna==2.7                 # via cryptography, requests
isodate==0.6.0            # via msrest
itsdangerous==1.1.0       # via flask
msrest==0.6.1             # via azure-mgmt-compute, azure-mgmt-network, msrestazure
msrestazure==0.5.1        # via azure-mgmt-compute, azure-mgmt-network, azure-mgmt-resource
oauthlib==2.1.0           # via requests-oauthlib
pycparser==2.19           # via cffi
pyjwt==1.6.4
python-dateutil==2.7.5    # via adal
requests-oauthlib==1.0.0  # via msrest
requests==2.20.1          # via adal, msrest, requests-oauthlib
six==1.11.0               # via cryptography, isodate, python-dateutil
urllib3==1.24.1           # via requests
```

As for DEBUG logs, sure, I can turn `logging.basicConfig(level=logging.DEBUG)` up, but it may take a while to get relevant logs :)

**Comment by lmazuel** [comment]
Thanks @akx 
I will re-read the ADAL about token refreshing and try to do a small experiment myself

**Comment by lmazuel** [comment]
@yugangw-msft any ideas why ADAL is not refreshing the token?

**Comment by akx** [comment]
@lmazuel Now that I'm not caching the `ServicePrincipalCredentials` as I originally had been (and instead trusting ADAL or whatever not to acquire real credentials too often), I haven't seen the exception -- at least not in the last 24 hours.

**Comment by yugangw-msft** [comment]
JFYI, there are no refresh tokens coming with the service principal auth flow. You need to hold on to the secret and get the token again; or use managed service identity so Azure will manage the secret for you.

**Comment by lmazuel** [comment]
@yugangw-msft but ADAL is doing this for free right? Seeing that the token is about to expire, and re-ask for it using the original credentials info?

**Comment by yugangw-msft** [comment]
ADAL will send you an exception. Do not manually crack open the token to see the expiration date unless you really have to, as the token format is more towards AAD's implementation details.

**Comment by lmazuel** [comment]
Hum, I just spent a few minutes inside ADAL, and I feel since I re-provide the credentials each call, ADAL will  look for the cache, invalidate the token if necessary, and re-do the query when necessary. Example of timeline:

- context.acquire_token_with_client_credentials(**credentials) # Will call and get the token and cache it
- context.acquire_token_with_client_credentials(**credentials) # Token in cache, return it
- context.acquire_token_with_client_credentials(**credentials) # Token in cache, return it
...
- context.acquire_token_with_client_credentials(**credentials) # Token in cache expired, empty cache, do a new call since I provide the credentials, cache the token and return it
- context.acquire_token_with_client_credentials(**credentials) # Token in cache, return it
...

Then, I never see an exception, and the call always succeed. Do I miss something?

**Comment by yugangw-msft** [comment]
If you has the credential available, you can always use `acquire_token_with_client_credentials`, as long as the credential is valid, then you are good .
I thought the flow would be:
1. you call `acquire_token_with_client_credentials` once to get the token, and the cache will be populated with the token which is good for a hour.
2.  In subsequent code, you call `acquire_token` which will always try to get the cached token
3. After a hour, the token gets expired and  you get the error from adal
4. You retrieve the secret from the secure source and call `acquire_token_with_client_credentials` again

of  course , if you don't mind caching the secret around in the memory all the time, then just call `acquire_token_with_client_credentials` :). We used to have a bug that expired token not get evicted which ended up corrupt the cache, but that one has been fixed

**Comment by lmazuel** [comment]
First, closing the issue, since the answer to the question is: ServicePrincipalCredentials is a long-lived and does not require additional work. @akx do not hesite to re-ask any questions if necessary.


@yugangw-msft yes, right now the instance keeps the parameters as instance field, and then in memory:
https://github.com/Azure/msrestazure-for-python/blob/35dc0e13240541e8991b796f164e248489cbb144/msrestazure/azure_active_directory.py#L353
We'll rediscuss later, and maybe in the context of MSAL how problematic it is (or not :))

**Comment by akx** [comment]
I'm still getting this exception sporadically – approximately every hour.

Could it be that [within `_internal_paging()`](https://github.com/Azure/azure-sdk-for-python/blob/09718bec64c2155bc179c862dbdf519677321ffd/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/operations/virtual_machines_operations.py#L867-L905) there's nothing to check whether the token we've acquired to start a possibly multi-paged operation is still viable while we're paginating?

**Comment by lmazuel** [comment]
Paging should have no impact, the internal workflow is the same.

If you see this every hour, may I ask you to activate DEBUG logging?
You need to activate HTTP saving as well:
```python
compute_client.config.enable_http_logger = True
```

You can either anonymise the logs, or send them to me by email directly \<my github alias\>@microsoft.com

**Comment by akx** [comment]
As it happens, after some changes last night to make our service do less concurrent requests (which it could have been doing from several threads), I haven't seen this exception in the last 18 hours...

I guess we can reclose this – sorry I'm not able to provide logs at this point.

**Comment by lmazuel** [comment]
@akx Feel free to re-open or re-discuss it any time :)

**Comment by afisayo** [comment]
I just started getting this on Azure Notebooks which I use quite extensively. Today is the first occurrence of this ever
