### ISSUE TITLE
Use of UserPassCredentials class moving forward?

### ISSUE THREAD

**Issue by kskvarci** [Azure/msrestazure-for-python#129]
Many users of the SDK are still leveraging the UserPassCredentials class. I realize that Microsoft documentation recommends agains the use of this class in favor of what I presume to be direct use of ADAL based on the verbiage: https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-legacy

Equivalent functionality in ADAL would be: acquire_token_with_username_password: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/authentication_context.py#L147

In looking at UserPassCredentials in the SDK however it is clear that this is using msrestazure: https://github.com/Azure/azure-sdk-for-python/blob/b678123b1d24d62df826085a7599c5edb6f6a472/azure-common/azure/common/credentials.py#L68

msrestazure under the covers is using ADAL and the above mentioned acquire_token_with_username_password.

So this being the case, the deprecated class is actually using the recommended class under the covers.

Is the general recommendation to just use ADAL directly and avoid the UserPassCredentials class as it may be removed in the future?

**Comment by lmazuel** [comment]
Hi @kskvarci 
"deprecated" in this situation doesn't mean "use ADAL instead", but means what ADAL team is saying here:
https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Acquiring-Tokens-with-username-and-password

> In general Microsoft does not advice customers to use it as it's less secure than the other flows, and it is not compatible with conditional access(because if the resource requires conditional access, the call to acquire token will just fail, given that this is not an interactive flow (the STS does not have an opportunity to present a dialog to the user to tell him/her that s/he needs to do multiple factor authentication).

But this library here is using ADAL, you get no benefits of using ADAL compared to msrestazure, on the contrary msrestazure sets more default than ADAL and it's easier :)
