### ISSUE TITLE
Cannot read HttpResponse body when HttpError is raised while fetching MSI Token 

### ISSUE THREAD

**Issue by aluong** [Azure/msrestazure-for-python#134]
When an [`HttpError` is thrown](https://github.com/Azure/msrestazure-for-python/blob/f5d7e687b8137cff69285307636417158b8c5b90/msrestazure/azure_active_directory.py#L704), the `response` is set to `result.raw`.  However, when the [token is fetched](https://github.com/Azure/msrestazure-for-python/blob/f5d7e687b8137cff69285307636417158b8c5b90/msrestazure/azure_active_directory.py#L685), we are not passing `stream=True` as described [here](https://2.python-requests.org/en/master/user/quickstart/#raw-response-content). Consequently, the message body cannot be read, because those bytes have been already read. 

The fix should be to just pass the parameter `stream=True` when making the `get` call.

**Comment by lmazuel** [comment]
I'm so sad I didn't catch that when this code was PR-ed, damn, now it's [integrated](https://github.com/yugangw-msft/azure-cli/blob/a1aaed240de7e7866c43625b212df8aa13f6a030/src/azure-cli-core/azure/cli/core/_profile.py#L309) in CLI and I cannot change it anymore.... Even if it violates the exception format itself (response should be a requests Response, not a urllib3 one).

`stream=True` might not solve your problem, see the last part of your link:

> An important note about using Response.iter_content versus Response.raw. Response.iter_content will automatically decode the gzip and deflate transfer-encodings. **Response.raw is a raw stream of bytes – it does not transform the response content**. If you really need access to the bytes as they were returned, use Response.raw.

You probably don't want to unzip the body and so on.... I'm technically not sure if it was gzip, but likely it is (most stuff are nowadays)

I'm adding a content attribute, that would act as the one from requests.Response, so at least you can act like it was one-ish:
https://github.com/Azure/msrestazure-for-python/pull/136

Thoughts?

**Comment by lmazuel** [comment]
@aluong being we put all effort on azure-identity, do you think it worth the effort here?

**Comment by lmazuel** [comment]
Closing, since the recommended approach now is officially to use azure-identity to pull MSI token
