### ISSUE TITLE
Parse resource id in scope of Management Group

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/msrestazure-for-python#139]
The following resource id for a [Blueprint ](https://aka.ms/BlueLocation) created under a [Management Group](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview) is treated as invalid with current [_ARMID_RE](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/tools.py#L34): `/providers/Microsoft.Management/managementGroups/myGroup/providers/Microsoft.Blueprint/blueprints/myBp`. 

Can you add support for parsing such resource ids?

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
