### ISSUE TITLE
Some error responses contain non-ascii, causing exceptions during error reporting.

### ISSUE THREAD

**Issue by nyetwurk** [Azure/msrestazure-for-python#140]
https://github.com/Azure/azure-cli/issues/12199#issuecomment-588350758

For example, the error for going over quota contains the word "Detail" with smart single quotes.

The proper solution is to eschew non-ascii but convincing MS (or Apple) to give up on smart quotes is probably not an option.

In the mean time,
```diff
ackages/msrestazure/azure_exceptions.py-dist /opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py
--- /opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py-dist	2020-02-19 17:34:04.707335477 +0000
+++ /opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py	2020-02-19 17:44:13.587230027 +0000
@@ -117,7 +117,7 @@
             for error_info in self.additionalInfo:
                 error_str += "\n\t{}".format(str(error_info).replace("\n", "\n\t"))
         error_bytes = error_str.encode()
-        return error_bytes.decode('ascii')
+        return error_bytes.decode('utf8')

     @classmethod
     def _get_subtype_map(cls):
```

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli/issues/12315
https://github.com/Azure/azure-cli/issues/12207
These issues report similar problems

**Comment by yungezz** [comment]
hi @lmazuel , will the issue be fixing in msrest.azure? Suppose no more fixing in existing runtime lib anymore

**Comment by lmazuel** [comment]
It has been fixed in 0.6.3, I forgot to close the issue, thanks!
https://github.com/Azure/msrestazure-for-python#2020-03-17-version-063

**Comment by nyetwurk** [comment]
https://github.com/Azure/msrestazure-for-python/commit/c132e2b093a3f17e8010a21066ccdbd1afa37b07

**Comment by nyetwurk** [comment]
https://github.com/Azure/msrestazure-for-python/pull/144

**Comment by qwordy** [comment]
Thank you so much! Laurent
