### ISSUE TITLE
Characters other than ascii are not supported in azure_exception's __str__ method

### ISSUE THREAD

**Issue by zhoxing-ms** [Azure/msrestazure-for-python#143]
The azure_exception's `__str__` method only supports the decode of ascii. If there are other special characters not in ascii code, it will cause exception, like: Ä and ä
[code link](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_exceptions.py#L120)

**Comment by lmazuel** [comment]
That's a good point, interesting is that this code is here since forever:
https://github.com/Azure/autorest/pull/1510/

Will patch that
