### ISSUE TITLE
Differing oauth_token depending on environment

### ISSUE THREAD

**Issue by James-Beckwith** [Azure/msrestazure-for-python#145]
When using the MSIAuthentication(...).token() function the return json is different depending on whether the function is a WebApp or not. This makes debugging frustrating as the same code couldn't used in local testing, on an Azure DSVM for instance, as in a WebApp without having to parse the returned json.

The main issue in question is that when MSIAuthentication(...).token() is run from a DSVM the returned json contains a "expires_in" key to denote how long until the token expires whilst when run in a WebApp in returns a json with a "expires_on" entry which is not only a different key but also a different format.

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
