### ISSUE TITLE
LongRunningOperation should probably not raise exception on HTTP 204 from requests using PATCH

### ISSUE THREAD

**Issue by fhoy** [Azure/msrestazure-for-python#146]
[LongRunningOperation._raise_if_bad_http_status_and_method()](https://github.com/Azure/msrestazure-for-python/blob/698eb06bcbf9fda4c7ae04d929f7b5b955fcbfed/msrestazure/polling/arm_polling.py#L128) currently raises `BadStatus` if HTTP 204 is returned from a PATCH request. With `azure-mgmt-apimanagement` 0.2.0, [updating a named value](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/namedvalue/update) (which uses PATCH) returns 204 on successful updates, and if this is the initial response, the code mentioned above is called, and execution fails. Even the [PATCH RFC](https://tools.ietf.org/html/rfc5789#section-2.1) uses a 204 response code as an example, so it seems that this combination should be allowed.

However, if I have misunderstood how the polling mechanism works, please let me know; although in that case it looks like `azure-mgmt-apimanagement` is doing something weird.

**Comment by lmazuel** [comment]
Hi @fhoy 
This has been fixed in azure-mgmt-core, which is the successor of this lib. All SDK will move their dependency to azure-mgmt-core before this summer.
Thanks!

**Comment by fhoy** [comment]
Good to know, thanks. Does that mean that there is no point in creating an issue for this in https://github.com/Azure/azure-sdk-for-python?

**Comment by lmazuel** [comment]
I think it's not necessary indeed, thanks!

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
