### ISSUE TITLE
MSIAuthentication does not cache token when running in Azure Functions (WebApps)

### ISSUE THREAD

**Issue by yogilad** [Azure/msrestazure-for-python#147]
We use `MSIAuthentication` class in Kusto Python SDK to allow customers to connect using managed service identity.
One of our customers has complained that the MSI endpoint occasionally reports HTTP errors, since it is overloaded with calls. 
(See: [azure-kusto-python issue 224](https://github.com/Azure/azure-kusto-python/issues/224))

When looking at the class there does not seem to be any caching layer if the token is retrieved using `get_msi_token` or`get_msi_token_webapp`. Only when `_ImdsTokenProvider` is used.

Is there a recommended way to use the library to retrieve MSI tokens in a way which is cached?
If not, can this capability be added to library (e.g. by moving the cache code from `_ImdsTokenProvider` to `MSIAuthentication`)?

**Comment by lmazuel** [comment]
The recommendation from the WebApp team was to call the endpoint all the time, that they will take care of the caching for us (since it's localhost, its not supposed to be overloaded...). I would contact the WebApp team to see if the recommendation changed here.

**Comment by yogilad** [comment]
Hi,
Is there any update with regard to WebApp team's recommendations on how to use the MSI endpoint?

**Comment by yogilad** [comment]
@lmazuel , is there a response from the webapp team?
We have another customer complaining about the same issue.

**Comment by lmazuel** [comment]
Closing, since the recommended approach now is officially to use azure-identity to pull MSI token
