### ISSUE TITLE
active directory does not use timeout argument

### ISSUE THREAD

**Issue by danield137** [Azure/msrestazure-for-python#148]
**Expected behaviour**: when providing a timeout argument to `MSIAuthentication`, it will be used to short circuit.

The root cause it not using the argument when issuing the actual rest call [here](https://github.com/Azure/msrestazure-for-python/blob/698eb06bcbf9fda4c7ae04d929f7b5b955fcbfed/msrestazure/azure_active_directory.py#L685)

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
