### ISSUE TITLE
ARMPolling update_status should also update progressComplete to report progress on cli commands

### ISSUE THREAD

**Issue by a-santamaria** [Azure/msrestazure-for-python#154]
For async operations ARM allows an optional header [azure-async-operation](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#call-action-post-asynchronously). And the format for the [response](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#operation-resource-format) allows to use the parameter percentComplete.

If this header azure-async-operation is used for long running operations, then ARMPolling [update_status ](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/polling/arm_polling.py#L439)should also update progressComplete so it can be used to report the progress of the long running operation [here](https://github.com/Azure/azure-cli/blob/04210197837bbceb547f86df7f086a42c96e0d2a/src/azure-cli-core/azure/cli/core/commands/__init__.py#L950.)

**Comment by lmazuel** [comment]
Thanks for the issue @a-santamaria , that's a fair feature request.

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
