### ISSUE TITLE
LongRunningOperation should handle polling operationStatus uri from location headers

### ISSUE THREAD

**Issue by sineadmcl13** [Azure/msrestazure-for-python#157]
As difference Resource Providers uses different methods of indicating async operations, there are three possible ways to poll on asynchronous Azure operations

By response headers
- Azure-AsyncOperation
- Location

By response body value
- provisioningState

[LongRunningOperation.get_status_from_location](https://github.com/Azure/msrestazure-for-python/blob/7986cdcc41d4131e1d6d866e8c80925921e25969/msrestazure/polling/arm_polling.py#L247) uses only the response code to determine the status. In cases where the location header points to an operationStatus uri, the result of the operation is in the body of this response and failures get swallowed, which is the case for async delete operations 

e.g Location header points to https://management.azure.com/subscriptions/{subscription-id}/providers/{provider}/locations/{region}/operations/{operation-id}?api-version=2019-12-01 which returns a 200 OK 
and response body
> {
"id":"/{subscription-id}/providers/{provider}/locations/{region}/operations/{operation-id}",
"name":"12541dd3-587f-4545-9e73-e777a93f74b0",
"status":"Failed",
"error":{"code":"ExecutionFailure","message":"Failing for test reasons"}
}

Location headers can be returned which should be handled in the same way that Azure-AsyncOperation headers so would it be possible to configure location header based polling to deterine the status from the response body

**Comment by lmazuel** [comment]
Hello. Location header is designed by the ARM spec to follow only the status code and nothing else, body is ignored on purpose
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#202-accepted-and-location-headers
