### ISSUE TITLE
Unreachable code in tests

### ISSUE THREAD

**Issue by langston-barrett** [Azure/msrestazure-for-python#158]
There are three places in the test suite with a statement that follows a `raise`. These statements are always unreachable.

https://github.com/Azure/msrestazure-for-python/blob/7986cdcc41d4131e1d6d866e8c80925921e25969/tests/test_arm_polling.py#L160-L161

https://github.com/Azure/msrestazure-for-python/blob/7986cdcc41d4131e1d6d866e8c80925921e25969/tests/test_operation.py#L126-L127

https://github.com/Azure/msrestazure-for-python/blob/7986cdcc41d4131e1d6d866e8c80925921e25969/tests/asynctests/test_async_arm_polling.py#L160-L161

**Comment by lmazuel** [comment]
Indeed, thanks for the issue! It's not hurting either right now, and this don't work actively on this library, but if I happen to work on it again will fix it ;). We accept PRs too :)
