### ISSUE TITLE
When authentication fails, the stack traces can reveal passwords in plaintext

### ISSUE THREAD

**Issue by ant0nsc** [Azure/msrestazure-for-python#162]
I just had an AzureDevOps pipeline run fail, where the `msrestazure` library threw an exception. The stacktrace contained the full password in plaintext. If that pipeline run had been on github actions, we would have revealed a password to the public.
Is there any chance of prevent such a thing? If yes, then I'd be happy to provide a more detailed description of the problematic setup here.

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
