### ISSUE TITLE
MSI: Failed to retrieve a token from Azure China

### ISSUE THREAD

**Issue by moritzxbe** [Azure/msrestazure-for-python#164]
MSI authentication fails for me in china. in azure global I use ad_credentials = MSIAuthentication() in my azure function but in china i get the following error message:
![image](https://user-images.githubusercontent.com/9870350/118013854-dbb9a900-b352-11eb-8c37-9548fa40f99b.png)

do I need to pass any parameter so that the function knows that I want to connect to azure china?

**Comment by adamdost-msft** [comment]
You need to ensure that you're setting the right Cloud Environment in the import module. It looks like you're defaulting to AZURE_PUBLIC and not AZURE_CHINA. Take a look [here](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain#using-pre-defined-sovereign-cloud-constants) for more info as to how to set it up.

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
