### ISSUE TITLE
MSI check for App Service uses incorrect checks

### ISSUE THREAD

**Issue by mattchenderson** [Azure/msrestazure-for-python#167]
The following checks are not inline with the actual behavior of these services:
https://github.com/Azure/msrestazure-for-python/blob/8849f398b6ebd4607de63c2f5d1318f44ec1d822/msrestazure/azure_active_directory.py#L552-L554
https://github.com/Azure/msrestazure-for-python/blob/8849f398b6ebd4607de63c2f5d1318f44ec1d822/msrestazure/azure_active_directory.py#L585

This for example will fail in Container Apps, and it impacts Azure CLI commands like `az login --identity`

The correct implementation would be to check for the combination IDENTITY_ENDPOINT and IDENTITY_HEADER. You can also check for MSI_ENDPOINT and MSI_SECRET, but these are just aliases to support legacy app behavior. The IDENTITY_ENDPOINT and IDENTITY_HEADER is the proper way to determine if you should be using the App Service protocol or IMDS.

Reference for the token service API can be found here: https://docs.microsoft.com/azure/app-service/overview-managed-identity#rest-endpoint-reference

**Comment by lmazuel** [comment]
Hi @mattchenderson 
This project is deprecated and no longer receives support. All recent (less than 2 years) SDKs now support `azure-identity` to provide MSI authentication with complete support from the team, to replace this library.
If you're stuck in a project that do requires msrestazure, please open an issue on azure-sdk-for-python to understand what we can do to help you move to `azure-identity`.
Thanks!
