### ISSUE TITLE
If using Azure-AsyncOperation, intermediate result is empty Model

### ISSUE THREAD

**Issue by lmazuel** [Azure/msrestazure-for-python#19]
Reference: https://github.com/Azure/azure-sdk-for-python/issues/1003

We try to parse `'{"status":"Running"}'` as a base model, and if someone is using `result` with a timeout, he gets an empty basic model.

FYI @annatisch

**Comment by runemy** [comment]
Any news for this issue? I'm also interessted in news on #18

**Comment by lmazuel** [comment]
Fixed a long ago
