### ISSUE TITLE
Get Attribute Error when calling result()

### ISSUE THREAD

**Issue by silencev** [Azure/msrestazure-for-python#21]
Calling **AzureOperationPoller.result()**  possibly get exception:
```python
AttributeError 'NoneType' object has no attribute 'resource'
```
Giving the short timeout value: **poller.result( timeout=1)** when the **send_cmd()** return lately [here](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L364). 
The variable self._operation is still **None**.

exception "Attribute" will be raised [here](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L474)

**Comment by lmazuel** [comment]
Good catch @silencev , thank you :)
