### ISSUE TITLE
ServicePrincinpalCredentials() and UserPassCredentials() do not change auth_endpoint

### ISSUE THREAD

**Issue by MagicChocoRolls** [Azure/msrestazure-for-python#22]
Hi there,

While I was trying to connect to different Azure instances I discovered that the hints from http://azure-sdk-for-python.readthedocs.io/en/latest/multicloud.html to connect to different clouds than the default do not work. This is because the functions _https() or more specifically _build_url() always use the string from self._auth_endpoint for URL creation, which is the URL for AzureUSA.

This results in AzureUSA-only connects. It would be cool to see an implementation that can use all different azure instances.

Regards

**Comment by lmazuel** [comment]
Hi @MagicChocoRolls 

You're totally, I get biased by my tests on Azure Government that actually use the same auth endpoint :(

In the meantime, you can get your token using [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-python), and use [this credentials in the SDK](http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal).

Thanks for reporting!

**Comment by lmazuel** [comment]
This is finally solved in msrestazure 0.4.11
https://github.com/Azure/msrestazure-for-python/releases/tag/v0.4.11
