### ISSUE TITLE
Hang on set_token() without timeout value

### ISSUE THREAD

**Issue by silencev** [Azure/msrestazure-for-python#30]
One of our python process hang at authentication
```python
credential = ServicePrincipalCredentials(client_id='ACCOUNT ID', secret='ACCOUNT SECRET ID', tenant='MY TENANT ID')
```
After checking the memory dump file, the root cause is no timeout value is specify [here](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py#L368)

Is it possible to expose the timeout parameter to let user set it?

**Comment by lmazuel** [comment]
Hi @silencev 
Sorry, for some reasons I missed your issue :(. This will be fixed in the next msrestazure to come
