### ISSUE TITLE
MSI: support appservice(web app, function app)

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/msrestazure-for-python#50]
Please check out the [document](https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity)
In case it helps, I tested out with [a sample](https://github.com/yugangw-msft/azure-site-test/tree/msi) in my repository. It was written in node, but should be straightforward to convert to Python.
EDIT: ~I suggest SDK clients should opt in with a flag, e.g. `MSIAuthentication(appService=true)`~ SDK 'MSIAuthentication' can detect the existence of `MSI_xxx` environment, then does the heavy lifting to acquire the token. 
(To enable MSI on webapps, for now, do it in portal. CLI will expose the support by the end of October)

//cc: @lmazuel, @mayurid, @skwan

**Comment by lmazuel** [comment]
I'm not a huge fan of `appService=true`. I think I will detect the presence of the environment variables `MSI_XXX`. Will try that asap.

**Comment by yugangw-msft** [comment]
> I think I will detect the presence of the environment variables MSI_XXX
@lmazuel, You have the flexible. Auto-detecting is fine. 
//cc:@amarzavery

**Comment by lmazuel** [comment]
msrestazure 0.4.15
