### ISSUE TITLE
 VSTS account creation Template deployment failed

### ISSUE THREAD

**Issue by nkv16786** [Azure/msrestazure-for-python#58]
I am trying to deploy this template using msrestazure : 

```json
{
  "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {},
  "resources": [
    {
      "name": "Crivs123",
      "type": "microsoft.visualstudio/account",
      "location": "centralus",
      "apiVersion": "2014-04-01-preview",
      "properties": {
       "accountName":"Crivs123",
       "operationType": "Create"
           },
      "resources": [
      ]
    }
  ]
}
```

but getting the error  :

```
  Azure Error: DeploymentFailed
        Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
        Exception Details:
                Error Code: BadRequest
                Message: {
          "code": "BadArgument",
          **"message": "The string must have at least one character.\r\nParameter name: accountName",**
          "target": "LegacyGetOrCreateBindPendingIdentity"
        }
                Target: None
```

The same template is working fine when deploy from the Azure portal

**Comment by lmazuel** [comment]
Hi @nkv16786 
msrestazure is a low level dependencies of SDK package, you should use azure-mgmt-resource package:
https://github.com/Azure-Samples/resource-manager-python-template-deployment

And since I didn't see your code, I can't help you right now :/

**Comment by nkv16786** [comment]
Here is my module::


        from azure.common.credentials import ServicePrincipalCredentials
        from azure.mgmt.resource import ResourceManagementClient
        from azure.mgmt.resource.resources.models import DeploymentMode
        import json
        import os
        import pdb
        import msrestazure.azure_operation
  


    
def deploy(clientid,clientsecret,tenantid,subscription_id,resourcegroup,parameters,deployment_name,template_name,location,deployment_mode=DeploymentMode.incremental):
        output={}
        try:


                credentials = ServicePrincipalCredentials(client_id=clientid,secret=clientsecret,tenant=tenantid)

                client = ResourceManagementClient(credentials,subscription_id)

                client.resource_groups.create_or_update(resourcegroup,{ 'location':location})

                opts = salt.config.minion_config('/etc/salt/master.d/integration.conf')
                basepath = opts["paas_template"]["path"]
                template_path = basepath+template_name
                if os.path.isfile(template_path):
                        with open(template_path, 'r') as template_file_fd:
                                template = json.load(template_file_fd)
                        output={}

                        parameter = salt.utils.sdbparse.sdb_to_string(parameters)
                        if "Unauthorized Access - Unable to find the account. Reason could be: No such account OR this account is not shared to you OR the access permission has been removed." in parameter.values():
                                output['result']=parameter['DbPassword']
                                output['status']=False
                                return output
                        else:
                                parameter = {key: {'value': value} for key, value in parameter.items()}

                                deployment_properties = {'mode': deployment_mode,'template':template,'parameters': parameter}

                                deployment_async_operation = client.deployments.create_or_update(resourcegroup,deployment_name,deployment_properties)

                                deployment_async_operation.wait()

                                existence= client.deployments.check_existence(resourcegroup,deployment_name)
                                if existence==True:
                                        result = deployment_async_operation.result()
                                        out=result.properties.outputs.items()
                                        pre_output={}
                                        for key,value in out:
                                                pre_output[key]=value["value"]
                                        output['result']=json.dumps(pre_output)
                                        output['status']=True
                                        return output
                                else:
                                        error="Your Deployment Failed..."
                                        output['result']=error
                                        output['status']=False
                                        return output
                else:
                        error="File not found at path : "+template_path
                        output['result']=error
                        output['status']=False
                        return output
        except  Exception as e:
#               pdb.set_trace()
                output['result']=e.__str__()
                output['status']=False
                return output

**Comment by nkv16786** [comment]
The template is successfully deployed directly on portal also this same module is being used for other 20 templates all of them are deployed successfully but only this vsts account creation template is creating a  problem is this a bug?

**Comment by lmazuel** [comment]
Sorry for the long answer, for closure on this, being the error it's likely an error in the `parameter` variable. If you still experience trouble, please create an issue in the main azure sdk for python repo:
https://github.com/Azure/azure-sdk-for-python
Thanks,
