### ISSUE TITLE
Keep Session (OAuth2Session) object as attribute somewhere to improve performance

### ISSUE THREAD

**Issue by lmazuel** [Azure/msrestazure-for-python#6]
A recent discussion shows me that keeping the Session object allows urllib to re-use the connection (connection pooling). 

> The Session object allows you to persist certain parameters across requests. It also persists cookies across all requests made from the Session instance, and will use urllib3's connection pooling. So if you're making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection).

`msrestazure` is not doing it currently and recreates a `OAuth2Session` (which inherits from `Session`) for each call.

This could be interesting to keep the session in the credentials instance and to re-use it. 

Multi-thread scenarios can be handled by creating one credentials instance per thread.

Thoughts @brettcannon @annatisch ?

**Comment by brettcannon** [comment]
If it works I don't see any negative.

**Comment by lmazuel** [comment]
Fixed with msrest 0.4.28 / msrestazure 0.4.27
