### ISSUE TITLE
_populate_from_metadata_endpoint suggestions

### ISSUE THREAD

**Issue by derekbekoe** [Azure/msrestazure-for-python#66]
https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_cloud.py#L198

1. Should the method be public?
It looks odd importing it as `from msrestazure.azure_cloud import _populate_from_metadata_endpoint`

2. `session` is not used in `session = requests.Session() if session is None else session`

**Comment by lmazuel** [comment]
1. No, I don't think this one should be public, but you can use it. You're like "protected" :)
2. Seriously, lol... I'll fix that.

**Comment by derekbekoe** [comment]
Sounds good
