### ISSUE TITLE
How to use AzureOperationPoller.add_done_callback() ?

### ISSUE THREAD

**Issue by GoldenMouse** [Azure/msrestazure-for-python#76]
I'm having trouble figuring out how to construct the callback function to use in AzureOperationPoller.add_done_callback(). What I'm trying to do is deallocate a VM after deployment has completed. Is this possible with this function?

**Comment by lmazuel** [comment]
Yes, that's legitimate. I don't have samples, but this should work (not tested):
```python
from msrestazure.azure_operation import finished, failed
def mycb(operation):
  if finished(operation.status) and not failed(operation.status):
     # Do something interesting

poller = client.operations.mylongrunningoperation(....)
poller.add_done_callback(mycb)
```

**Comment by GoldenMouse** [comment]
Thank you this works like a charm. Now I have to figure out how to do this asynchronously in python so the routine doesn't have to wait to finish when user submits a web request.

**Comment by lmazuel** [comment]
If you're using Python >= 3.5, we are adding the support for asyncio currently and should be there soon.
https://github.com/Azure/azure-sdk-for-python/issues/496

**Comment by lmazuel** [comment]
Closing, be follow the async state on the mentionned issue. Thanks!
