### ISSUE TITLE
AzureOperationPoller exception deserializing certain ARM deployment errors

### ISSUE THREAD

**Issue by tjprescott** [Azure/msrestazure-for-python#78]
See https://github.com/Azure/azure-cli/issues/5590

I have a template to repro this issue:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "sites_tjpwebapp1_name": {
      "defaultValue": "tjpwebapp1",
      "type": "String"
    },
    "config_web_name": {
      "defaultValue": "boohansi",
      "type": "String"
    },
    "hostNameBindings_tjpwebapp1.azurewebsites.net_name": {
      "defaultValue": "test.com",
      "type": "String"
    },
    "sites_tjpwebapp1_serverFarmId": {
      "type": "String",
	  "defaultValue": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/tjp-plan/providers/Microsoft.Web/serverfarms/plan1"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Web/sites",
      "kind": "app",
      "name": "[parameters('sites_tjpwebapp1_name')]",
      "apiVersion": "2016-08-01",
      "location": "West US",
      "scale": null,
      "properties": {
        "enabled": true,
        "hostNameSslStates": [
          {
            "name": "[concat(parameters('sites_tjpwebapp1_name'),'.azurewebsites.net')]",
            "sslState": "Disabled",
            "virtualIP": null,
            "thumbprint": null,
            "toUpdate": null,
            "hostType": "Standard"
          },
          {
            "name": "[concat(parameters('sites_tjpwebapp1_name'),'.scm.azurewebsites.net')]",
            "sslState": "Disabled",
            "virtualIP": null,
            "thumbprint": null,
            "toUpdate": null,
            "hostType": "Repository"
          }
        ],
        "serverFarmId": "[parameters('sites_tjpwebapp1_serverFarmId')]",
        "reserved": false,
        "siteConfig": null,
        "scmSiteAlsoStopped": false,
        "hostingEnvironmentProfile": null,
        "clientAffinityEnabled": true,
        "clientCertEnabled": false,
        "hostNamesDisabled": false,
        "containerSize": 0,
        "dailyMemoryTimeQuota": 0,
        "cloningInfo": null
      },
      "dependsOn": []
    },
    {
      "type": "Microsoft.Web/sites/config",
      "name": "[concat(parameters('sites_tjpwebapp1_name'), '/', parameters('config_web_name'))]",
      "apiVersion": "2016-08-01",
      "location": "West US",
      "scale": null,
      "properties": {
        "numberOfWorkers": 1,
        "defaultDocuments": [
          "Default.htm",
          "Default.html",
          "Default.asp",
          "index.htm",
          "index.html",
          "iisstart.htm",
          "default.aspx",
          "index.php",
          "hostingstart.html"
        ],
        "netFrameworkVersion": "v4.0",
        "phpVersion": "5.6",
        "pythonVersion": "",
        "nodeVersion": "",
        "linuxFxVersion": "",
        "requestTracingEnabled": false,
        "remoteDebuggingEnabled": false,
        "remoteDebuggingVersion": null,
        "httpLoggingEnabled": false,
        "logsDirectorySizeLimit": 35,
        "detailedErrorLoggingEnabled": false,
        "publishingUsername": "[concat('$tjp', parameters('config_web_name'),'app1')]",
        "publishingPassword": null,
        "appSettings": null,
        "metadata": null,
        "connectionStrings": null,
        "machineKey": null,
        "handlerMappings": null,
        "documentRoot": null,
        "scmType": "None",
        "use32BitWorkerProcess": true,
        "webSocketsEnabled": false,
        "alwaysOn": false,
        "javaVersion": null,
        "javaContainer": null,
        "javaContainerVersion": null,
        "appCommandLine": "",
        "managedPipelineMode": "Integrated",
        "virtualApplications": [
          {
            "virtualPath": "/",
            "physicalPath": "site\\wwwroot",
            "preloadEnabled": false,
            "virtualDirectories": null
          }
        ],
        "winAuthAdminState": 0,
        "winAuthTenantState": 0,
        "customAppPoolIdentityAdminState": false,
        "customAppPoolIdentityTenantState": false,
        "runtimeADUser": null,
        "runtimeADUserPassword": null,
        "loadBalancing": "LeastRequests",
        "routingRules": [],
        "experiments": {
          "rampUpRules": []
        },
        "limits": null,
        "autoHealEnabled": false,
        "autoHealRules": null,
        "tracingOptions": null,
        "vnetName": "",
        "siteAuthEnabled": false,
        "siteAuthSettings": {
          "enabled": null,
          "unauthenticatedClientAction": null,
          "tokenStoreEnabled": null,
          "allowedExternalRedirectUrls": null,
          "defaultProvider": null,
          "clientId": null,
          "clientSecret": null,
          "issuer": null,
          "allowedAudiences": null,
          "additionalLoginParams": null,
          "isAadAutoProvisioned": false,
          "googleClientId": null,
          "googleClientSecret": null,
          "googleOAuthScopes": null,
          "facebookAppId": null,
          "facebookAppSecret": null,
          "facebookOAuthScopes": null,
          "twitterConsumerKey": null,
          "twitterConsumerSecret": null,
          "microsoftAccountClientId": null,
          "microsoftAccountClientSecret": null,
          "microsoftAccountOAuthScopes": null
        },
        "cors": null,
        "push": null,
        "apiDefinition": null,
        "autoSwapSlotName": null,
        "localMySqlEnabled": false,
        "managedServiceIdentityId": null,
        "ipSecurityRestrictions": null
      },
      "dependsOn": [
        "[resourceId('Microsoft.Web/sites', parameters('sites_tjpwebapp1_name'))]"
      ]
    },
    {
      "type": "Microsoft.Web/sites/hostNameBindings",
      "name": "[concat(parameters('sites_tjpwebapp1_name'), '/', parameters('hostNameBindings_tjpwebapp1.azurewebsites.net_name'))]",
      "apiVersion": "2016-08-01",
      "location": "West US",
      "scale": null,
      "properties": {
        "siteName": "tjpwebapp1",
        "domainId": null,
        "hostNameType": "Verified"
      },
      "dependsOn": [
        "[resourceId('Microsoft.Web/sites', parameters('sites_tjpwebapp1_name'))]"
      ]
    }
  ]
}
```

If you try to deploy this you'll get an error that the ServerFarm is not found. However, possibly due to the structure of the error message from ARM, msrestazure encounters an error. Instead of raising an exception though, it seems to deserialize it anyways, placing all the error properties into an "additionalProperties" field.  This doesn't normally happen.

**CLI Logging Statements**
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.1 (Windows-10-10.0.16299-SP0) requests/2.18.4 msrest/0.4.27 msrest_azure/0.4.22 resourcemanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.30'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': 'a68ef0ae-27d3-11e8-b88e-a0b3ccf7272a'
msrest.http_logger :     'CommandName': 'group deployment create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14935'
msrest.http_logger :     'x-ms-request-id': 'aad2b930-cf05-40ea-9f1f-2a71a97bb97f'
msrest.http_logger :     'x-ms-correlation-request-id': 'aad2b930-cf05-40ea-9f1f-2a71a97bb97f'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS2:20180314T220455Z:aad2b930-cf05-40ea-9f1f-2a71a97bb97f'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 14 Mar 2018 22:04:55 GMT'
msrest.http_logger :     'Content-Length': '514'
msrest.http_logger : Response content:
msrest.http_logger : b'{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"NotFound","message":"{\\r\\n  \\"Code\\": \\"NotFound\\",\\r\\n  \\"Message\\": \\"Cannot find ServerFarm with name plan1.\\",\\r\\n  \\"Target\\": null,\\r\\n  \\"Details\\": [\\r\\n    {\\r\\n      \\"Message\\": \\"Cannot find ServerFarm with name plan1.\\"\\r\\n    },\\r\\n    {\\r\\n      \\"Code\\": \\"NotFound\\"\\r\\n    },\\r\\n    {\\r\\n      \\"ErrorEntity\\": {\\r\\n        \\"ExtendedCode\\": \\"51004\\",\\r\\n        \\"MessageTemplate\\": \\"Cannot find {0} with name {1}.\\",\\r\\n        \\"Parameters\\": [\\r\\n          \\"ServerFarm\\",\\r\\n          \\"plan1\\"\\r\\n        ],\\r\\n        \\"Code\\": \\"NotFound\\",\\r\\n        \\"Message\\": \\"Cannot find ServerFarm with name plan1.\\"\\r\\n      }\\r\\n    }\\r\\n  ],\\r\\n  \\"Innererror\\": null\\r\\n}"}]}}'

**msrestazure prints this stack trace**
Exception in thread AzureOperationPoller(48ce0bbe-a5d0-4bcf-91a7-09fa610cb420):
Traceback (most recent call last):
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_operation.py", line 377, in _start
    self._poll(update_cmd)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_operation.py", line 464, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.azure_operation.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_operation.py", line 388, in _start
    self._exception = CloudError(self._response)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_exceptions.py", line 157, in __init__
    self._build_error_data(response)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_exceptions.py", line 173, in _build_error_data
    self.error = self.deserializer('CloudErrorRoot', response).error
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1023, in __call__
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1187, in deserialize_data
    return self(obj_type, data)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1023, in __call__
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1176, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1203, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1203, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1187, in deserialize_data
    return self(obj_type, data)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1030, in __call__
    return self._instantiate_model(response, d_attrs, additional_properties)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrest\serialization.py", line 1132, in _instantiate_model
    response_obj = response(**kwargs)
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_exceptions.py", line 62, in __init__
    self.message = kwargs.get('message')
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\msrestazure\azure_exceptions.py", line 114, in message
    value = eval(value)
  File "<string>", line 4, in <module>
NameError: name 'null' is not defined

** Back to CLI logging statements **
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x055FBDB0>, <function _x509_from_base64_to_hex_transform at 0x055FBDF8>]
Event: CommandInvoker.OnFilterResult []

** The final deserialized object the CLI outputs **
{
  "additionalProperties": {
    "error": {
      "code": "DeploymentFailed",
      "details": [
        {
          "code": "NotFound",
          "message": "{\r\n  \"Code\": \"NotFound\",\r\n  \"Message\": \"Cannot find ServerFarm with name plan1.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"Cannot find ServerFarm with name plan1.\"\r\n    },\r\n    {\r\n      \"Code\": \"NotFound\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"51004\",\r\n        \"MessageTemplate\": \"Cannot find {0} with name {1}.\",\r\n        \"Parameters\": [\r\n          \"ServerFarm\",\r\n          \"plan1\"\r\n        ],\r\n        \"Code\": \"NotFound\",\r\n        \"Message\": \"Cannot find ServerFarm with name plan1.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
        }
      ],
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
    },
    "status": "Failed"
  },
  "id": null,
  "name": null,
  "properties": null
}

**Comment by lmazuel** [comment]
*This package is deprecated and no longer receives updates*

- The authentication part of this package has been moved to [azure-identity](https://pypi.org/project/azure-identity/)
- The other parts of this library are covered by [azure-mgmt-core](https://pypi.org/project/azure-mgmt-core/)

As such, we will no longer accept PR and fix issues on this project, and this repo will be soon archived.
