### ISSUE TITLE
--ids not working for az backup item set-policy command

### ISSUE THREAD

**Issue by dragonfly91** [Azure/msrestazure-for-python#80]
This command needs **vault_name**, **container_name** and **item_name** and my plan is to fetch all these 3 from the **--ids** parameter. I've declared the params like so:
```
    with self.argument_context('backup item') as c:
        c.argument('vault_name', vault_name_type, id_part='name')
        c.argument('container_name', container_name_type)

    with self.argument_context('backup item show') as c:
        c.argument('name', item_name_type, options_list=['--name', '-n'], help='Name of the backed up item. You can use the backup item list command to get the name of a backed up item.')

    with self.argument_context('backup item set-policy') as c:
        c.argument('vault_name', vault_name_type, id_part='child_name_3')
        c.argument('container_name', container_name_type, id_part='child_name_1')
        c.argument('item_name', item_name_type, options_list=['--name', '-n'], id_part='name', help='Name of the backed up item. You can use the backup item list command to get the name of a backed up item.')
        c.argument('policy_name', policy_name_type, help='Name of the Backup policy. You can use the backup policy list command to get the name of a backup policy.')
```
When I run the command, I get the following error:

```
(env) d:\MabOneSdk\cli>az backup item set-policy --ids "/Subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/vsarg-sea-RS-1606/providers/Microsoft.RecoveryServices/vaults/vsarg-sea-RS-1606/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainer;canarytestvm1;vsarg-1705-li/protectedItems/VM;iaasvmcontainer;canarytestvm1;vsarg-1705-li" -p DefaultPolicy -debug
az backup item set-policy: error: argument --ids: invalid ResourceId value: '/Subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/vsarg-sea-RS-1606/providers/Microsoft.RecoveryServices/vaults/vsarg-sea-RS-1606/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainer;canarytestvm1;vsarg-1705-li/protectedItems/VM;iaasvmcontainer;canarytestvm1;vsarg-1705-li'
```

**Comment by lmazuel** [comment]
Hi @dragonfly91 , for what I see, it's a CLI issue, could you open a CLI issue first? This lib here is more lowlevel that your issue. Thanks

**Comment by dragonfly91** [comment]
@lmazuel The issue was that - looks like the is_valid_resource_id method (which is now in msrestazure.tools) does not recognize our ID format. Can you please look into this bug? Our ID looks like: /Subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/vsarg-sea-RS-1606/providers/Microsoft.RecoveryServices/vaults/vsarg-sea-RS-1606/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainer;canarytestvm1;vsarg-1705-li/protectedItems/VM;iaasvmcontainer;canarytestvm1;vsarg-1705-li

**Comment by lmazuel** [comment]
@williexu Seems there is a bug in parse ID, thought?

**Comment by williexu** [comment]
@dragonfly91  The resource id parser tool does not match for ids that started with capitalized "Subscription" as in your example.
https://github.com/Azure/msrestazure-for-python/pull/81 should fix this.

**Comment by dragonfly91** [comment]
Thanks! Waiting for the fix 👍
