### ISSUE TITLE
UserPassCredentials: support ws-trust flow for federated AAD account 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/msrestazure-for-python#93]
The pertinent code is [here](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py#L405-L413), per the latest suggestion from AAD group, for federated accounts we should use ws-trust to acquire tokens from ADFS on-prem instead of directly posting the request to the AAD endpoint, which will not work in new tenant.
A few options to fix this:
1. Use ADAL
2. Port the logic from ADAL
3. Deprecate this 
4. Do not default to CLI's first-party app-id

//cc: @lmazuel

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/msrestazure-for-python/pull/94

**Comment by lmazuel** [comment]
msrestazure 0.5.0
https://github.com/Azure/msrestazure-for-python/pull/111
