### ISSUE TITLE
Resource ID helper methods do not work for some IDs.

### ISSUE THREAD

**Issue by tjprescott** [Azure/msrestazure-for-python#98]
See https://github.com/Azure/azure-cli/issues/6475

The Resource Explorer allows you to invoke a GET (CLI `show`) on an ID of this form:
`/subscriptions/{subscription-id}/resources`

This is supported by the resource REST API. However, when this ID is passed through msrestazure, you get the following error:

az resource: error: argument --ids: invalid ResourceId value: '/subscriptions/{subscription-id}/resources'

**Comment by lmazuel** [comment]
@williexu please :)

**Comment by williexu** [comment]
That is not a ARM resource ID, it's a rest endpoint that can be used to list resources.

**Comment by tjprescott** [comment]
After discussion with the team, we feel the appropriate fix (if any) would be in the CLI itself, rather than the parse ID methods. I'll close this for now.
