### ISSUE TITLE
Managed Identity/IMDS auth: Configurable retry time-out. 

### ISSUE THREAD

**Issue by arluca** [Azure/msrestazure-for-python#99]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation can make the current thread wait for as long as 15 minutes. For response time sensitive services this might not be acceptable. It could also result in service unavailability if all threads are blocked for a token to be generated when a sudden burst arrives after a cold start.
The developer may want to fast fail after certain time interval says for example 10 seconds if the call is still failing.

Can we make the retry max configurable?

**Comment by lmazuel** [comment]
Make sense, let me think about the best implementation and come back to you.

**Comment by lmazuel** [comment]
Hi @arluca 
If you need to cap the maximum possible of time precisely, best would be to use a `ThreadPoolExecutor` (didn't actually executed the code, might need adjustment):
```python
from concurrent.futures import ThreadPoolExecutor, TimeOut
from msrestazure.azure_active_directory import MSIAuthentication

max_wait_time_in_seconds = 10
credentials = MSIAuthentication()
with ThreadPoolExecutor() as executor:
    future = executor.submit(credentials.set_token)
    try:
        future.result(max_wait_time_in_seconds)
    except TimeOut:
        raise ValueError("Unable to get a MSI token in {} seconds".format(max_wait_time_in_seconds))
```

If you don't need precise time, I should be able to give access to all parameters that are like [Retry of urllib3](https://github.com/urllib3/urllib3/blob/master/urllib3/util/retry.py) . Meaning, backoff factor, max retry, etc. that ultimately controls the maximum amount of time (but not precisely)

FYI @yugangw-msft

**Comment by arluca** [comment]
@lmazuel : Could you share an example? While the ask was for specifying specific time (seconds), I can share this method as well.
